In [1]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [2]:
print('Chaves do conjunto Iris: \n{}'.format(iris_dataset.keys()))

Chaves do conjunto Iris: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [3]:
print('Nomes das categorias: {}'.format(iris_dataset['target_names']))
print('Nomes das características: {}'.format(iris_dataset['feature_names']))
print('Shape dos dados de entrada: {}'.format(iris_dataset['data'].shape))
print('Cinco primeiros elementos do conjunto: \n{}'.format(iris_dataset['data'][:5]))
print('Shape da saída esperada (categorias): {}'.format(iris_dataset['target'].shape))
print('Saída esperada: {}'.format(iris_dataset['target']))

Nomes das categorias: ['setosa' 'versicolor' 'virginica']
Nomes das características: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Shape dos dados de entrada: (150, 4)
Cinco primeiros elementos do conjunto: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Shape da saída esperada (categorias): (150,)
Saída esperada: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state=0
)

In [13]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

In [14]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [15]:
import numpy as np

In [16]:
X_new = np.array([[4.9, 3 ,1.4, 0.2]])
prediction = knn.predict(X_new)
print('Previsão: {}'.format(prediction))
print('Categoria prevista: {}'.format(iris_dataset['target_names'][prediction]))

Previsão: [0]
Categoria prevista: ['setosa']


In [17]:
y_pred = knn.predict(X_test)
print('Previsões para o conjunto de teste:\n {}'.format(y_pred))

Previsões para o conjunto de teste:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [18]:
print('Acurácia do conjunto de teste: {:.2f}'.format(knn.score(X_test, y_test)))

Acurácia do conjunto de teste: 0.97
